trigger:
  - azure-pipelines
  - azure/*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      yarn install
    displayName: 'install dependencies'

  - script: |
      node scripts/sizeSnapshot/upload $(variables['AWS_SECRET_ACCESS_KEY'])
    displayName: 'persist size snapshot'
