defaults: &defaults
  working_directory: /tmp/material-ui
  docker:
    - image: circleci/openjdk:8-jdk-node-browsers
# CircleCI has disabled the cache across forks for security reasons.
# Following their official statement, it was a quick solution, they
# are working on providing this feature back with appropriate security measures.
# https://discuss.circleci.com/t/saving-cache-stopped-working-warning-skipping-this-step-disabled-in-configuration/24423/21
#
# restore_repo: &restore_repo
#   restore_cache:
#     key: v1-repo-{{ .Branch }}-{{ .Revision }}
install_js: &install_js
  run:
    name: Install js dependencies
    command: |
      yarn config set yarn-offline-mirror ~/.cache/npm-packages-offline-cache/v1
      yarn
restore_yarn_cache: &restore_yarn_cache
  restore_cache:
    key: v2-yarn-sha-{{ checksum "yarn.lock" }}
restore_yarn_offline_mirror: &restore_yarn_offline_mirror
  restore_cache:
    key: v2-npm-packages-offline-cache
version: 2.1
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *restore_yarn_offline_mirror
      - *restore_yarn_cache
      - run:
          name: Check versions and env
          command: |
            yarn --version
            node --version
            docker --version
            docker-compose --version
            env
            yarn cache dir
      - *install_js
      - run:
          name: Should not have any git not staged
          command: git diff --exit-code
      - save_cache:
          key: v2-yarn-sha-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn/v4
      - save_cache:
          key: v2-npm-packages-offline-cache
          paths:
            - ~/.cache/npm-packages-offline-cache/v1